### ISSUE TITLE
[bug] AttributeError: 'Namespace' object has no attribute 'auth_domain'

### ISSUE THREAD

**Issue by p0dalirius** [p0dalirius/Coercer#80]
```
$ ./Coercer.py scan -d LAB -u 'Administrator' -p 'Admin123!' --target-ip 10.0.0.201
       ______
      / ____/___  ___  _____________  _____
     / /   / __ \/ _ \/ ___/ ___/ _ \/ ___/
    / /___/ /_/ /  __/ /  / /__/  __/ /      v2.4.3
    \____/\____/\___/_/   \___/\___/_/       by @podalirius_

Traceback (most recent call last):
  File "/data/git_projects/p0dalirius/Coercer/./Coercer.py", line 11, in <module>
    main()
  File "/data/git_projects/p0dalirius/Coercer/coercer/__main__.py", line 216, in main
    domain=options.auth_domain,
           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'auth_domain'```

**Comment by p0dalirius** [comment]
Working as of d7624bee80a323aa23b4df30ed62642604e80490

![image](https://github.com/user-attachments/assets/7d46b1f1-a880-498c-8c6c-30e76f5900fa)
